# Generated by Django 4.1.2 on 2022-12-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coctails_clean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coctail',
            name='image',
            field=models.FileField(default=None, upload_to='images'),
        ),
    ]
