# Generated by Django 4.1.2 on 2022-12-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coctails_clean', '0004_alter_coctail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coctail',
            name='image',
        ),
    ]
