# Generated by Django 4.1.2 on 2022-11-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_homeworkstatus_homework_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
