# Generated by Django 4.1.2 on 2022-11-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_alter_homework_views_count'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='homework',
            table='hausaufgabe',
        ),
    ]
