# Generated by Django 4.1.2 on 2022-11-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_alter_homework_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='homework.homeworkstatus', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
